swagger: '2.0'
info:
  version: '1.0'
  title: quasar LoanPrograms
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: quasarloanprograms.us-west-2.elasticbeanstalk.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /v1/loanprograms:
    get:
      description: ''
      summary: GetLoadProgramsByTenantIdAndClientIdAndProgramId
      tags:
      - LoanPrograms v1
      operationId: V1LoanprogramsGet2
      produces:
      - application/json
      parameters:
      - name: clientId
        in: header
        required: true
        type: string
        description: ''
      - name: tenantId
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /v1/loanprograms
          headers:
            clientId: 10
            tenantId: 10
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: GetLoadProgramsByTenantIdAndClientIdAndProgramId
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      description: ''
      summary: PostLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: V1LoanprogramsPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PostLoadProgramsByTenantIdAndClientIdRequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: clientId
        in: header
        required: true
        type: string
        description: ''
      - name: tenantId
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /v1/loanprograms
          headers:
            Content-Type: application/json
            clientId: 10
            tenantId: 10
          body: >-
            {

            	"programId": 6,

            	"programName": "Rustic Granite Pizza 6",

            	"isActive": 1

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: PostLoadProgramsByTenantIdAndClientId
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/loanprograms/6:
    put:
      description: ''
      summary: PutLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: V1Loanprograms6Put
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PutLoadProgramsByTenantIdAndClientIdRequest'
      - name: clientId
        in: header
        required: true
        type: string
        description: ''
      - name: tenantId
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /v1/loanprograms/6
          headers:
            Content-Type: application/json
            clientId: 10
            tenantId: 10
          body: >-
            {

            	"programId": 6,

            	"programName": "Rustic Granite Pizza 6.1",

            	"isActive": 1

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: PutLoadProgramsByTenantIdAndClientId
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      description: ''
      summary: DeleteLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: V1Loanprograms6Delete
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DeleteLoadProgramsByTenantIdAndClientIdRequest'
      - name: clientId
        in: header
        required: true
        type: string
        description: ''
      - name: tenantId
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /v1/loanprograms/6
          headers:
            Content-Type: application/json
            clientId: 10
            tenantId: 10
          body: >-
            {
              "programId": "2",
              "programName": "Loan Program 2"
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: DeleteLoadProgramsByTenantIdAndClientId
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/loanprograms/2:
    patch:
      description: ''
      summary: PatchLoadProgramsByTenantIdAndClientId
      tags:
      - LoanPrograms v1
      operationId: V1Loanprograms2Patch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PatchLoadProgramsByTenantIdAndClientIdRequest'
      - name: clientId
        in: header
        required: true
        type: string
        description: ''
      - name: tenantId
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /v1/loanprograms/2
          headers:
            Content-Type: application/json
            clientId: 10
            tenantId: 10
          body: >-
            {
              "programName": "Loan Program 2.1"
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: PatchLoadProgramsByTenantIdAndClientId
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/loanprogramtemplates:
    get:
      description: Get All Loan Program Templates
      summary: Get All Loan Program Templates
      tags:
      - Loan Programs Template v1
      operationId: V1LoanprogramtemplatesGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GetAllLoanProgramTemplatesresponse'
          examples:
            application/json:
              data:
              - CreatedDate: 2017-09-15
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.9899999999998
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      AutoPayIncentive: 0.25
                      MaxRate: 6
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                UpdatedDate: 2017-9-15
                TemplateName: KristinTest2
                Version: 1.0
                IsActive: true
                Description: This is an updated template for Kristin
                Id: KristinTest
              - UpdatedDate: 2017-09-15 10:25:19.147
                CreatedDate: 2017-09-15 10:25:19.147
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.9899999999998
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      MaxRate: 6
                      AutoPayIncentive: 0.25
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                Version: 1.0
                TemplateName: BasePersonalFixed
                IsActive: true
                Description: BasePersonalFixed
                Id: 9d90a944-438a-4763-9d25-f60ec33bf4f3
              - UpdatedDate: 2017-09-15 10:28:19.147
                CreatedDate: 2017-09-15 10:28:19.147
                Settings:
                  PaymentApplication:
                    Order: Fees/Interest/Principal
                    AllowPaidAhead: No
                  ReduceTerm:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: HardshipForbearance
                  Fees:
                    NSF:
                      PercentOrDollar: Amount
                      Minimum: 0
                      Maximum: 0
                      Amount: 20
                    Late:
                      PercentOrDollar: Percent
                      Minimum: 0
                      Maximum: 9999.9899999999998
                      DaysLate: 15
                      Statuses:
                      - Status: Repayment
                      - Status: Bankruptcy
                      - Status: Claim
                      Amount: 5
                  InterestAccrual:
                    Statuses:
                    - Status: Repayment
                      AutoPayIncentive: 0.25
                    - Status: MilitaryRepayment
                      MaxRate: 6
                      AutoPayIncentive: 0.25
                    - Status: Bankruptcy
                    - Status: Claim
                    - Status: Default
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Method: Actual/Actual
                  Billing:
                    Statuses:
                    - Status: Repayment
                    - Status: MilitaryRepayment
                    - Status: HardshipForbearance
                    - Status: DisasterForbearance
                    Frequency: Monthly
                    Days: 21
                Version: 1.0
                TemplateName: BasePersonal Variable
                IsActive: true
                Description: BasePersonalFixed
                Id: 8db8875c-3396-4c64-baac-e4a77436b9c8
              statusDescription: OK
              statusCode: 200
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /v1/loanprogramtemplates
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: RAW
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            content-encoding: gzip
            content-length: 681
            content-type: application/json; charset=utf-8
            date: Mon, 18 Sep 2017 22:04:18 GMT
            etag: W/"e7c-vUPOBXXej+UKhOmIGuWRGXaQQVA"
            server: nginx/1.10.2
            x-powered-by: Express
          body: '{"data":[{"CreatedDate":"2017-09-15","Settings":{"PaymentApplication":{"Order":"Fees/Interest/Principal","AllowPaidAhead":"No"},"ReduceTerm":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"HardshipForbearance"}]},"Fees":{"NSF":{"PercentOrDollar":"Amount","Minimum":0,"Maximum":0,"Amount":20},"Late":{"PercentOrDollar":"Percent","Minimum":0,"Maximum":9999.99,"DaysLate":15,"Statuses":[{"Status":"Repayment"},{"Status":"Bankruptcy"},{"Status":"Claim"}],"Amount":5}},"InterestAccrual":{"Statuses":[{"Status":"Repayment","AutoPayIncentive":0.25},{"Status":"MilitaryRepayment","AutoPayIncentive":0.25,"MaxRate":6},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"Default"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Method":"Actual/Actual"},"Billing":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Days":21}},"UpdatedDate":"2017-9-15","TemplateName":"KristinTest2","Version":"1.0","IsActive":true,"Description":"This is an updated template for Kristin","Id":"KristinTest"},{"UpdatedDate":"2017-09-15 10:25:19.147","CreatedDate":"2017-09-15 10:25:19.147","Settings":{"PaymentApplication":{"Order":"Fees/Interest/Principal","AllowPaidAhead":"No"},"ReduceTerm":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"HardshipForbearance"}]},"Fees":{"NSF":{"PercentOrDollar":"Amount","Minimum":0,"Maximum":0,"Amount":20},"Late":{"PercentOrDollar":"Percent","Minimum":0,"Maximum":9999.99,"DaysLate":15,"Statuses":[{"Status":"Repayment"},{"Status":"Bankruptcy"},{"Status":"Claim"}],"Amount":5}},"InterestAccrual":{"Statuses":[{"Status":"Repayment","AutoPayIncentive":0.25},{"Status":"MilitaryRepayment","MaxRate":6,"AutoPayIncentive":0.25},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"Default"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Method":"Actual/Actual"},"Billing":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Days":21}},"Version":"1.0","TemplateName":"BasePersonalFixed","IsActive":true,"Description":"BasePersonalFixed","Id":"9d90a944-438a-4763-9d25-f60ec33bf4f3"},{"UpdatedDate":"2017-09-15 10:28:19.147","CreatedDate":"2017-09-15 10:28:19.147","Settings":{"PaymentApplication":{"Order":"Fees/Interest/Principal","AllowPaidAhead":"No"},"ReduceTerm":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"HardshipForbearance"}]},"Fees":{"NSF":{"PercentOrDollar":"Amount","Minimum":0,"Maximum":0,"Amount":20},"Late":{"PercentOrDollar":"Percent","Minimum":0,"Maximum":9999.99,"DaysLate":15,"Statuses":[{"Status":"Repayment"},{"Status":"Bankruptcy"},{"Status":"Claim"}],"Amount":5}},"InterestAccrual":{"Statuses":[{"Status":"Repayment","AutoPayIncentive":0.25},{"Status":"MilitaryRepayment","MaxRate":6,"AutoPayIncentive":0.25},{"Status":"Bankruptcy"},{"Status":"Claim"},{"Status":"Default"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Method":"Actual/Actual"},"Billing":{"Statuses":[{"Status":"Repayment"},{"Status":"MilitaryRepayment"},{"Status":"HardshipForbearance"},{"Status":"DisasterForbearance"}],"Frequency":"Monthly","Days":21}},"Version":"1.0","TemplateName":"BasePersonal Variable","IsActive":true,"Description":"BasePersonalFixed","Id":"8db8875c-3396-4c64-baac-e4a77436b9c8"}],"statusDescription":"OK","statusCode":200}'
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get All Loan Program Templates
        x-testDescription: Get All Loan Program Templates
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/loanprogramtemplates/BasePersonal Variable1:
    get:
      description: Get All Loan Program Templates by Template Name
      summary: Get All Loan Program Templates by Template Name
      tags:
      - Loan Programs Template v1
      operationId: V1LoanprogramtemplatesBasePersonalVariable1Get
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /v1/loanprogramtemplates/BasePersonal Variable1
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get All Loan Program Templates by Template Name
        x-testDescription: Get All Loan Program Templates by Template Name
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v2/loanprograms:
    get:
      description: Get Client Specific Templates
      summary: Get Client Specific Templates
      tags:
      - Loan Program v2
      operationId: V2LoanprogramsGet
      produces:
      - application/json
      parameters:
      - name: tenantid
        in: header
        required: true
        type: string
        description: ''
      - name: clientid
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /v2/loanprograms
          headers:
            tenantid: 1
            clientid: 2
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Client Specific Templates
        x-testDescription: Get Client Specific Templates
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v2/loanprograms/BasePersonalFixed:
    get:
      description: Get Client Specific Templates by Template Name
      summary: Get Client Specific Templates by Template Name
      tags:
      - Loan Program v2
      operationId: V2LoanprogramsBasePersonalFixedGet
      produces:
      - application/json
      parameters:
      - name: tenantid
        in: header
        required: true
        type: string
        description: ''
      - name: clientid
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /v2/loanprograms/BasePersonalFixed
          headers:
            tenantid: 1
            clientid: 2
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Client Specific Templates by Template Name
        x-testDescription: Get Client Specific Templates by Template Name
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  GetLoadProgramsByTenantIdAndClientIdResponse:
    title: GetLoadProgramsByTenantIdAndClientIdResponse
    example:
      rowCount: 3
      data:
      - ProgramId: 2
        ProgramName: Loan Program 2.1
        ProgramType: null
        BaseRate: null
        RateChangeFrequency: null
        InterestAccrualMethod: null
        IsActive: 0
      - ProgramId: 4
        ProgramName: Loan Program 4
        ProgramType: null
        BaseRate: null
        RateChangeFrequency: null
        InterestAccrualMethod: null
        IsActive: 0
      - ProgramId: 6
        ProgramName: Rustic Granite Pizza 6.1
        ProgramType: null
        BaseRate: null
        RateChangeFrequency: null
        InterestAccrualMethod: null
        IsActive: 1
      statusDescription: OK
      statusCode: 200
    type: object
    properties:
      rowCount:
        description: ''
        example: 3
        type: integer
        format: int32
      data:
        description: ''
        example:
        - ProgramId: 2
          ProgramName: Loan Program 2.1
          ProgramType: null
          BaseRate: null
          RateChangeFrequency: null
          InterestAccrualMethod: null
          IsActive: 0
        - ProgramId: 4
          ProgramName: Loan Program 4
          ProgramType: null
          BaseRate: null
          RateChangeFrequency: null
          InterestAccrualMethod: null
          IsActive: 0
        - ProgramId: 6
          ProgramName: Rustic Granite Pizza 6.1
          ProgramType: null
          BaseRate: null
          RateChangeFrequency: null
          InterestAccrualMethod: null
          IsActive: 1
        type: array
        items:
          $ref: '#/definitions/Datum'
      statusDescription:
        description: ''
        example: OK
        type: string
      statusCode:
        description: ''
        example: 200
        type: integer
        format: int32
    required:
    - rowCount
    - data
    - statusDescription
    - statusCode
  Datum:
    title: Datum
    example:
      ProgramId: 2
      ProgramName: Loan Program 2.1
      ProgramType: null
      BaseRate: null
      RateChangeFrequency: null
      InterestAccrualMethod: null
      IsActive: 0
    type: object
    properties:
      ProgramId:
        description: ''
        example: 2
        type: integer
        format: int32
      ProgramName:
        description: ''
        example: Loan Program 2.1
        type: string
      ProgramType:
        description: ''
        type: string
      BaseRate:
        description: ''
        type: string
      RateChangeFrequency:
        description: ''
        type: string
      InterestAccrualMethod:
        description: ''
        type: string
      IsActive:
        description: ''
        example: 0
        type: integer
        format: int32
    required:
    - ProgramId
    - ProgramName
    - ProgramType
    - BaseRate
    - RateChangeFrequency
    - InterestAccrualMethod
    - IsActive
  PostLoadProgramsByTenantIdAndClientIdRequest:
    title: PostLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: 6
      programName: Rustic Granite Pizza 6
      isActive: 1
    type: object
    properties:
      programId:
        description: ''
        example: 6
        type: integer
        format: int32
      programName:
        description: ''
        example: Rustic Granite Pizza 6
        type: string
      isActive:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - programId
    - programName
    - isActive
  PutLoadProgramsByTenantIdAndClientIdRequest:
    title: PutLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: 6
      programName: Rustic Granite Pizza 6.1
      isActive: 1
    type: object
    properties:
      programId:
        description: ''
        example: 6
        type: integer
        format: int32
      programName:
        description: ''
        example: Rustic Granite Pizza 6.1
        type: string
      isActive:
        description: ''
        example: 1
        type: integer
        format: int32
    required:
    - programId
    - programName
    - isActive
  DeleteLoadProgramsByTenantIdAndClientIdRequest:
    title: DeleteLoadProgramsByTenantIdAndClientIdRequest
    example:
      programId: 2
      programName: Loan Program 2
    type: object
    properties:
      programId:
        description: ''
        example: 2
        type: string
      programName:
        description: ''
        example: Loan Program 2
        type: string
    required:
    - programId
    - programName
  PatchLoadProgramsByTenantIdAndClientIdRequest:
    title: PatchLoadProgramsByTenantIdAndClientIdRequest
    example:
      programName: Loan Program 2.1
    type: object
    properties:
      programName:
        description: ''
        example: Loan Program 2.1
        type: string
    required:
    - programName
  GetAllLoanProgramTemplatesresponse:
    title: Get All Loan Program TemplatesResponse
    example:
      data:
      - CreatedDate: 2017-09-15
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.9899999999998
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              AutoPayIncentive: 0.25
              MaxRate: 6
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        UpdatedDate: 2017-9-15
        TemplateName: KristinTest2
        Version: 1.0
        IsActive: true
        Description: This is an updated template for Kristin
        Id: KristinTest
      - UpdatedDate: 2017-09-15 10:25:19.147
        CreatedDate: 2017-09-15 10:25:19.147
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.9899999999998
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              MaxRate: 6
              AutoPayIncentive: 0.25
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        Version: 1.0
        TemplateName: BasePersonalFixed
        IsActive: true
        Description: BasePersonalFixed
        Id: 9d90a944-438a-4763-9d25-f60ec33bf4f3
      - UpdatedDate: 2017-09-15 10:28:19.147
        CreatedDate: 2017-09-15 10:28:19.147
        Settings:
          PaymentApplication:
            Order: Fees/Interest/Principal
            AllowPaidAhead: No
          ReduceTerm:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: Bankruptcy
            - Status: Claim
            - Status: HardshipForbearance
          Fees:
            NSF:
              PercentOrDollar: Amount
              Minimum: 0
              Maximum: 0
              Amount: 20
            Late:
              PercentOrDollar: Percent
              Minimum: 0
              Maximum: 9999.9899999999998
              DaysLate: 15
              Statuses:
              - Status: Repayment
              - Status: Bankruptcy
              - Status: Claim
              Amount: 5
          InterestAccrual:
            Statuses:
            - Status: Repayment
              AutoPayIncentive: 0.25
            - Status: MilitaryRepayment
              MaxRate: 6
              AutoPayIncentive: 0.25
            - Status: Bankruptcy
            - Status: Claim
            - Status: Default
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Method: Actual/Actual
          Billing:
            Statuses:
            - Status: Repayment
            - Status: MilitaryRepayment
            - Status: HardshipForbearance
            - Status: DisasterForbearance
            Frequency: Monthly
            Days: 21
        Version: 1.0
        TemplateName: BasePersonal Variable
        IsActive: true
        Description: BasePersonalFixed
        Id: 8db8875c-3396-4c64-baac-e4a77436b9c8
      statusDescription: OK
      statusCode: 200
    type: object
    properties:
      data:
        description: ''
        example:
        - CreatedDate: 2017-09-15
          Settings:
            PaymentApplication:
              Order: Fees/Interest/Principal
              AllowPaidAhead: No
            ReduceTerm:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: Bankruptcy
              - Status: Claim
              - Status: HardshipForbearance
            Fees:
              NSF:
                PercentOrDollar: Amount
                Minimum: 0
                Maximum: 0
                Amount: 20
              Late:
                PercentOrDollar: Percent
                Minimum: 0
                Maximum: 9999.9899999999998
                DaysLate: 15
                Statuses:
                - Status: Repayment
                - Status: Bankruptcy
                - Status: Claim
                Amount: 5
            InterestAccrual:
              Statuses:
              - Status: Repayment
                AutoPayIncentive: 0.25
              - Status: MilitaryRepayment
                AutoPayIncentive: 0.25
                MaxRate: 6
              - Status: Bankruptcy
              - Status: Claim
              - Status: Default
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Method: Actual/Actual
            Billing:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Days: 21
          UpdatedDate: 2017-9-15
          TemplateName: KristinTest2
          Version: 1.0
          IsActive: true
          Description: This is an updated template for Kristin
          Id: KristinTest
        - UpdatedDate: 2017-09-15 10:25:19.147
          CreatedDate: 2017-09-15 10:25:19.147
          Settings:
            PaymentApplication:
              Order: Fees/Interest/Principal
              AllowPaidAhead: No
            ReduceTerm:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: Bankruptcy
              - Status: Claim
              - Status: HardshipForbearance
            Fees:
              NSF:
                PercentOrDollar: Amount
                Minimum: 0
                Maximum: 0
                Amount: 20
              Late:
                PercentOrDollar: Percent
                Minimum: 0
                Maximum: 9999.9899999999998
                DaysLate: 15
                Statuses:
                - Status: Repayment
                - Status: Bankruptcy
                - Status: Claim
                Amount: 5
            InterestAccrual:
              Statuses:
              - Status: Repayment
                AutoPayIncentive: 0.25
              - Status: MilitaryRepayment
                MaxRate: 6
                AutoPayIncentive: 0.25
              - Status: Bankruptcy
              - Status: Claim
              - Status: Default
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Method: Actual/Actual
            Billing:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Days: 21
          Version: 1.0
          TemplateName: BasePersonalFixed
          IsActive: true
          Description: BasePersonalFixed
          Id: 9d90a944-438a-4763-9d25-f60ec33bf4f3
        - UpdatedDate: 2017-09-15 10:28:19.147
          CreatedDate: 2017-09-15 10:28:19.147
          Settings:
            PaymentApplication:
              Order: Fees/Interest/Principal
              AllowPaidAhead: No
            ReduceTerm:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: Bankruptcy
              - Status: Claim
              - Status: HardshipForbearance
            Fees:
              NSF:
                PercentOrDollar: Amount
                Minimum: 0
                Maximum: 0
                Amount: 20
              Late:
                PercentOrDollar: Percent
                Minimum: 0
                Maximum: 9999.9899999999998
                DaysLate: 15
                Statuses:
                - Status: Repayment
                - Status: Bankruptcy
                - Status: Claim
                Amount: 5
            InterestAccrual:
              Statuses:
              - Status: Repayment
                AutoPayIncentive: 0.25
              - Status: MilitaryRepayment
                MaxRate: 6
                AutoPayIncentive: 0.25
              - Status: Bankruptcy
              - Status: Claim
              - Status: Default
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Method: Actual/Actual
            Billing:
              Statuses:
              - Status: Repayment
              - Status: MilitaryRepayment
              - Status: HardshipForbearance
              - Status: DisasterForbearance
              Frequency: Monthly
              Days: 21
          Version: 1.0
          TemplateName: BasePersonal Variable
          IsActive: true
          Description: BasePersonalFixed
          Id: 8db8875c-3396-4c64-baac-e4a77436b9c8
        type: array
        items:
          $ref: '#/definitions/Datum7'
      statusDescription:
        description: ''
        example: OK
        type: string
      statusCode:
        description: ''
        example: 200
        type: integer
        format: int32
    required:
    - data
    - statusDescription
    - statusCode
  Datum7:
    title: Datum7
    example:
      CreatedDate: 2017-09-15
      Settings:
        PaymentApplication:
          Order: Fees/Interest/Principal
          AllowPaidAhead: No
        ReduceTerm:
          Statuses:
          - Status: Repayment
          - Status: MilitaryRepayment
          - Status: Bankruptcy
          - Status: Claim
          - Status: HardshipForbearance
        Fees:
          NSF:
            PercentOrDollar: Amount
            Minimum: 0
            Maximum: 0
            Amount: 20
          Late:
            PercentOrDollar: Percent
            Minimum: 0
            Maximum: 9999.9899999999998
            DaysLate: 15
            Statuses:
            - Status: Repayment
            - Status: Bankruptcy
            - Status: Claim
            Amount: 5
        InterestAccrual:
          Statuses:
          - Status: Repayment
            AutoPayIncentive: 0.25
          - Status: MilitaryRepayment
            AutoPayIncentive: 0.25
            MaxRate: 6
          - Status: Bankruptcy
          - Status: Claim
          - Status: Default
          - Status: HardshipForbearance
          - Status: DisasterForbearance
          Frequency: Monthly
          Method: Actual/Actual
        Billing:
          Statuses:
          - Status: Repayment
          - Status: MilitaryRepayment
          - Status: HardshipForbearance
          - Status: DisasterForbearance
          Frequency: Monthly
          Days: 21
      UpdatedDate: 2017-9-15
      TemplateName: KristinTest2
      Version: 1.0
      IsActive: true
      Description: This is an updated template for Kristin
      Id: KristinTest
    type: object
    properties:
      CreatedDate:
        description: ''
        example: 2017-09-15
        type: string
      Settings:
        $ref: '#/definitions/Settings'
      UpdatedDate:
        description: ''
        example: 2017-9-15
        type: string
      TemplateName:
        description: ''
        example: KristinTest2
        type: string
      Version:
        description: ''
        example: 1.0
        type: string
      IsActive:
        description: ''
        example: true
        type: boolean
      Description:
        description: ''
        example: This is an updated template for Kristin
        type: string
      Id:
        description: ''
        example: KristinTest
        type: string
    required:
    - CreatedDate
    - Settings
    - UpdatedDate
    - TemplateName
    - Version
    - IsActive
    - Description
    - Id
  Settings:
    title: Settings
    example:
      PaymentApplication:
        Order: Fees/Interest/Principal
        AllowPaidAhead: No
      ReduceTerm:
        Statuses:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: Bankruptcy
        - Status: Claim
        - Status: HardshipForbearance
      Fees:
        NSF:
          PercentOrDollar: Amount
          Minimum: 0
          Maximum: 0
          Amount: 20
        Late:
          PercentOrDollar: Percent
          Minimum: 0
          Maximum: 9999.9899999999998
          DaysLate: 15
          Statuses:
          - Status: Repayment
          - Status: Bankruptcy
          - Status: Claim
          Amount: 5
      InterestAccrual:
        Statuses:
        - Status: Repayment
          AutoPayIncentive: 0.25
        - Status: MilitaryRepayment
          AutoPayIncentive: 0.25
          MaxRate: 6
        - Status: Bankruptcy
        - Status: Claim
        - Status: Default
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        Frequency: Monthly
        Method: Actual/Actual
      Billing:
        Statuses:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        Frequency: Monthly
        Days: 21
    type: object
    properties:
      PaymentApplication:
        $ref: '#/definitions/PaymentApplication'
      ReduceTerm:
        $ref: '#/definitions/ReduceTerm'
      Fees:
        $ref: '#/definitions/Fees'
      InterestAccrual:
        $ref: '#/definitions/InterestAccrual'
      Billing:
        $ref: '#/definitions/Billing'
    required:
    - PaymentApplication
    - ReduceTerm
    - Fees
    - InterestAccrual
    - Billing
  PaymentApplication:
    title: PaymentApplication
    example:
      Order: Fees/Interest/Principal
      AllowPaidAhead: No
    type: object
    properties:
      Order:
        description: ''
        example: Fees/Interest/Principal
        type: string
      AllowPaidAhead:
        description: ''
        example: No
        type: string
    required:
    - Order
    - AllowPaidAhead
  ReduceTerm:
    title: ReduceTerm
    example:
      Statuses:
      - Status: Repayment
      - Status: MilitaryRepayment
      - Status: Bankruptcy
      - Status: Claim
      - Status: HardshipForbearance
    type: object
    properties:
      Statuses:
        description: ''
        example:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: Bankruptcy
        - Status: Claim
        - Status: HardshipForbearance
        type: array
        items:
          $ref: '#/definitions/Status'
    required:
    - Statuses
  Status:
    title: Status
    example:
      Status: Repayment
    type: object
    properties:
      Status:
        description: ''
        example: Repayment
        type: string
    required:
    - Status
  Fees:
    title: Fees
    example:
      NSF:
        PercentOrDollar: Amount
        Minimum: 0
        Maximum: 0
        Amount: 20
      Late:
        PercentOrDollar: Percent
        Minimum: 0
        Maximum: 9999.9899999999998
        DaysLate: 15
        Statuses:
        - Status: Repayment
        - Status: Bankruptcy
        - Status: Claim
        Amount: 5
    type: object
    properties:
      NSF:
        $ref: '#/definitions/NSF'
      Late:
        $ref: '#/definitions/Late'
    required:
    - NSF
    - Late
  NSF:
    title: NSF
    example:
      PercentOrDollar: Amount
      Minimum: 0
      Maximum: 0
      Amount: 20
    type: object
    properties:
      PercentOrDollar:
        description: ''
        example: Amount
        type: string
      Minimum:
        description: ''
        example: 0
        type: integer
        format: int32
      Maximum:
        description: ''
        example: 0
        type: integer
        format: int32
      Amount:
        description: ''
        example: 20
        type: integer
        format: int32
    required:
    - PercentOrDollar
    - Minimum
    - Maximum
    - Amount
  Late:
    title: Late
    example:
      PercentOrDollar: Percent
      Minimum: 0
      Maximum: 9999.9899999999998
      DaysLate: 15
      Statuses:
      - Status: Repayment
      - Status: Bankruptcy
      - Status: Claim
      Amount: 5
    type: object
    properties:
      PercentOrDollar:
        description: ''
        example: Percent
        type: string
      Minimum:
        description: ''
        example: 0
        type: integer
        format: int32
      Maximum:
        description: ''
        example: 9999.9899999999998
        type: number
        format: double
      DaysLate:
        description: ''
        example: 15
        type: integer
        format: int32
      Statuses:
        description: ''
        example:
        - Status: Repayment
        - Status: Bankruptcy
        - Status: Claim
        type: array
        items:
          $ref: '#/definitions/Status'
      Amount:
        description: ''
        example: 5
        type: integer
        format: int32
    required:
    - PercentOrDollar
    - Minimum
    - Maximum
    - DaysLate
    - Statuses
    - Amount
  InterestAccrual:
    title: InterestAccrual
    example:
      Statuses:
      - Status: Repayment
        AutoPayIncentive: 0.25
      - Status: MilitaryRepayment
        AutoPayIncentive: 0.25
        MaxRate: 6
      - Status: Bankruptcy
      - Status: Claim
      - Status: Default
      - Status: HardshipForbearance
      - Status: DisasterForbearance
      Frequency: Monthly
      Method: Actual/Actual
    type: object
    properties:
      Statuses:
        description: ''
        example:
        - Status: Repayment
          AutoPayIncentive: 0.25
        - Status: MilitaryRepayment
          AutoPayIncentive: 0.25
          MaxRate: 6
        - Status: Bankruptcy
        - Status: Claim
        - Status: Default
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        type: array
        items:
          $ref: '#/definitions/Status17'
      Frequency:
        description: ''
        example: Monthly
        type: string
      Method:
        description: ''
        example: Actual/Actual
        type: string
    required:
    - Statuses
    - Frequency
    - Method
  Status17:
    title: Status17
    example:
      Status: Repayment
      AutoPayIncentive: 0.25
    type: object
    properties:
      Status:
        description: ''
        example: Repayment
        type: string
      AutoPayIncentive:
        description: ''
        example: 0.25
        type: number
        format: double
      MaxRate:
        description: ''
        example: 6
        type: integer
        format: int32
    required:
    - Status
  Billing:
    title: Billing
    example:
      Statuses:
      - Status: Repayment
      - Status: MilitaryRepayment
      - Status: HardshipForbearance
      - Status: DisasterForbearance
      Frequency: Monthly
      Days: 21
    type: object
    properties:
      Statuses:
        description: ''
        example:
        - Status: Repayment
        - Status: MilitaryRepayment
        - Status: HardshipForbearance
        - Status: DisasterForbearance
        type: array
        items:
          $ref: '#/definitions/Status'
      Frequency:
        description: ''
        example: Monthly
        type: string
      Days:
        description: ''
        example: 21
        type: integer
        format: int32
    required:
    - Statuses
    - Frequency
    - Days
